package Pertemuan8;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.JOptionPane;

public class NewJFrame1 extends javax.swing.JFrame {
    int l=1000, t=800;
    int x0=l/2, y0=t/2;
            
    int lebar, tinggi;
    double pX, pY, tX, tY;
    
    Graphics g;
    double[][] oby=new double[4][2];
    double[][] tv=new double[4][4];
    
    public NewJFrame1() {
        initComponents();
        setSize(l,t);
        setLocationRelativeTo(null);
        setResizable(false);
        this.getContentPane().setBackground(Color.yellow);
        setTitle("alif daud f.");
        x_pX.requestFocus();
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        g.setColor(Color.red);
        g.drawLine(0, y0, l, y0);
        g.setColor(Color.blue);
        g.drawLine(x0, 0, x0, t);
        
        g.setFont(new Font("Times New Roman", Font.BOLD, 12));
        g.setColor(Color.black);
        g.drawString("Sumbu X", x0+330, y0-(-20));
        g.drawString("Sumbu Y", x0+10, y0-250);
        g.drawString("0,0", x0-8, y0+13);
        
    }
    
    public double[][] obyek2d(double oby[][]){
     pX=Double.parseDouble(x_pX.getText());
     pY=Double.parseDouble(x_pY.getText());
     oby[1][1]=pX;
     oby[2][1]=pY;
     oby[3][1]=1;
     this.oby=oby;
     return this.oby;
    }
    
    public void gambarAwal(){
        g = getGraphics();
        lebar=Integer.parseInt(x_l.getText());
        tinggi=Integer.parseInt(x_t.getText());
        
        g.setColor(Color.red);
        g.fillRect((int)(x0+pX),(int)(y0-pY),lebar,tinggi);
    }
    
    public void gerakgambar(){
        g.fillRect((int)(x0+oby[1][1]), (int)(y0-oby[2][1]),lebar,tinggi);
    }
    
    public double [][] matrikstranformOby (double [][] oby, double [][] tr){
    double hasil[][]=new double[4][2];
    
    for(int i=1;i<=3;i++){
        hasil [i][1]=0;
    for(int j=1;j<=3;j++){
        hasil[i][1]+=tr[i][j]*oby[j][1];
    }
    }
    this.oby=hasil;
    return this.oby;
    }
    
    public double [][] matrikstranslasasi(double[][] tv, double tx, double ty){
        tv[1][1]=1;     tv[1][2]=0;     tv[1][3]=tx;
        tv[2][1]=0;     tv[2][2]=1;     tv[2][3]=ty;
        tv[3][1]=0;     tv[3][2]=0;     tv[3][3]=1;
        
        this.tv=tv;
        return this.tv;    
    }
    public void panggil(){
        g=getGraphics();
        tX=Double.parseDouble(x_tX.getText());
        tY=Double.parseDouble(x_tY.getText());
        obyek2d(oby);
        matrikstranslasasi(tv,tX,tY);
        matrikstranformOby(oby,tv);
        gambarAwal();
        g.setColor(Color.blue);
        gerakgambar();
    }
    
    public void panggilLambat(){
        g=getGraphics();
        tX=Double.parseDouble(x_tX.getText());
        tY=Double.parseDouble(x_tY.getText());
        double stepX=0, stepY=0;
        
        while(Math.abs(stepX)<=Math.abs(tX)){
            try{
                obyek2d(oby);
                matrikstranslasasi(tv,stepX,stepY);
                matrikstranformOby(oby,tv);
                gambarAwal();
                
                g.setColor(Color.pink);
                gerakgambar();
                Thread.sleep(200);
                g.setColor(Color.white);
                gerakgambar();
                stepX += tX/20; stepY += tY/20;
                
            }catch(Exception e){
            }
        }
        g.setColor(Color.black);
        gerakgambar();
        stepX=0;
        stepY=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        x_tX = new javax.swing.JTextField();
        x_pX = new javax.swing.JTextField();
        x_tY = new javax.swing.JTextField();
        x_pY = new javax.swing.JTextField();
        x_l = new javax.swing.JTextField();
        x_t = new javax.swing.JTextField();
        x_gc = new javax.swing.JButton();
        x_gl = new javax.swing.JButton();
        x_hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tx");

        jLabel2.setText("Ty");

        jLabel3.setText("Px");

        jLabel4.setText("pY");

        jLabel5.setText("L");

        jLabel6.setText("T");

        x_tX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_tXActionPerformed(evt);
            }
        });

        x_pX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_pXActionPerformed(evt);
            }
        });

        x_tY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_tYActionPerformed(evt);
            }
        });

        x_pY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_pYActionPerformed(evt);
            }
        });

        x_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_lActionPerformed(evt);
            }
        });

        x_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_tActionPerformed(evt);
            }
        });

        x_gc.setText("Gerak Cepat");
        x_gc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_gcActionPerformed(evt);
            }
        });

        x_gl.setText("Gerak Lambat");
        x_gl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_glActionPerformed(evt);
            }
        });

        x_hapus.setText("Hapus");
        x_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x_pX, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x_pY, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x_tX, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x_tY, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addComponent(x_l, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(x_t, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(x_gc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_gl)
                    .addComponent(x_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(x_gc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(x_gl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(x_hapus)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x_tX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_tY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x_pX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_pY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void x_tXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_tXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_tXActionPerformed

    private void x_pXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_pXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_pXActionPerformed

    private void x_tYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_tYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_tYActionPerformed

    private void x_pYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_pYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_pYActionPerformed

    private void x_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_lActionPerformed

    private void x_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_tActionPerformed

    private void x_gcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_gcActionPerformed
           int cekL,cekT;
        cekL=Integer.parseInt(x_l.getText());
        cekT=Integer.parseInt(x_t.getText());
        
        if(x_pX.getText().isEmpty() || x_pY.getText().isEmpty() || x_l.getText().isEmpty() ||
                x_t.getText().isEmpty() || x_tX.getText().isEmpty() || x_tY.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "salah satu kolom masih kosong, isi dulu", "WARNING!",
                    JOptionPane.WARNING_MESSAGE);
        }
        else if(cekL<1 || cekT<1){
            JOptionPane.showMessageDialog(this, "kolom L dan T harus berupa bilangan asli", "ISI LAGI",
                    JOptionPane.WARNING_MESSAGE);
        }
        else{
            panggil();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_x_gcActionPerformed

    private void x_glActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_glActionPerformed
 int cekL,cekT;
        cekL=Integer.parseInt(x_l.getText());
        cekT=Integer.parseInt(x_t.getText());
        
        if(x_pX.getText().isEmpty() || x_pY.getText().isEmpty() || x_l.getText().isEmpty() ||
                x_t.getText().isEmpty() || x_tX.getText().isEmpty() || x_tY.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "salah satu kolom masih kosong, isi dulu", "WARNING!",
                    JOptionPane.WARNING_MESSAGE);
        }
        else if(cekL<1 || cekT<1){
            JOptionPane.showMessageDialog(this, "kolom L dan T harus berupa bilangan asli", "ISI LAGI",
                    JOptionPane.WARNING_MESSAGE);
        }
        else{
            panggilLambat();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_x_glActionPerformed

    private void x_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_hapusActionPerformed
 g=getGraphics();
        repaint();       // TODO add your handling code here:
    }//GEN-LAST:event_x_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton x_gc;
    private javax.swing.JButton x_gl;
    private javax.swing.JButton x_hapus;
    private javax.swing.JTextField x_l;
    private javax.swing.JTextField x_pX;
    private javax.swing.JTextField x_pY;
    private javax.swing.JTextField x_t;
    private javax.swing.JTextField x_tX;
    private javax.swing.JTextField x_tY;
    // End of variables declaration//GEN-END:variables
}
